package org.ming.connect.enums;

public enum Common {
    LOGIN,
    CREATE_ROOM, LOGIN_SUCCESS, CREATE_ROOM_SUCCESS, QUERY_ROOM, QUERY_ROOM_SUCCESS, ENTER_ROOM, ENTER_ROOM_SUCCESS, GAME_START, GAME_OK, EXIT_ROOM, EXIT_ROOM_SUCCESS, UPDATE_ROOM, GAME_STARTING, SYN_GAME, INIT_GAME, INIT_PLAYER, SYN_PLAYER, INIT_GAME_SUCCESS, WAIT_INIT_GAME, KEYDOWN, KEYUP, SYN_GAME_REMOVE, SYN_GAME_ADD, SYN_GAME_BUBBLE, WAIT_INIT_PLAYER;
}
